let suggestions = [
    "Tunis", 
    "Ariana", 
    "Ben Arous", 
    "Mannouba", 
    "Bizerte", 
    "Nabeul", 
    "Beja", 
    "Jendouba", 
    "Zaghouan", 
    "Siliana", 
    "Le Kef", 
    "Sousse", 
    "Monastir", 
    "Mahdia", 
    "Kasserine", 
    "Sidi Bouzid", 
    "Kairouan", 
    "Gafsa", 
    "Sfax", 
    "Gabès", 
    "Médenine", 
    "Tozeur", 
    "Kebili", 
    "Tataouine"
];